### ISSUE TITLE
Add hyperterm-show-frame package

### ISSUE THREAD

**Issue by benjcalderon** [bnb/awesome-hyper#188]
[hyperterm-show-frame](https://www.npmjs.com/package/hyperterm-show-frame)

This package is designed to remove the default frameless setting on hyperterm allowing tiling WM like bspwm and i3 to draw a border on it.

When the frame is enabled it also enables the top menu so this plugin also takes care of that and removes the hides the menu

**Comment by iamstarkov** [comment]
sup @benjcalderon, i believe you in how your plugin works. that said there are several issues.

0) hyperterm had been renamed to hyper, so should every theme and plugin
a) there is no documentation in your package
b) there is no picture illustrating how does it look

you can add your package to lists in these repo by submitting a pull-request instead of issue, but please fix aforementioned issues. 

Feel free to ask for help if something confuses your.
