### ISSUE TITLE
Hyper cat not working

### ISSUE THREAD

**Issue by jordan-miguel** [bnb/awesome-hyper#290]
When I first started using hyper I added the cat cursor `'hyper-cat-cursor',`.

Now for some reason it has gone. The string is still in my hyper.js file & hyper is up to date.

Is there something that I'm not aware of that's possibly conflicting this?

**Comment by delcore92** [comment]
Hi @jordan-miguel,

Try disabling all other installed plugins and themes to see if that fixes the issue. If so, it's likely that there's a conflict between a plugin and `hyper-cat-cursor`. Use the process of elimination to find which plugin that is and remove it. 

Otherwise, it's probably best to raise this question against the [hyper-cat-cursor repository](https://github.com/balazssagi/hyper-cat-cursor).

It's also worth checking if you are running Hyper v2. In v2, they have swapped out the underlying terminal, hterm, in favour of xterm, which significantly changed the interface many plugins rely on. If that's the case, just set your update `updateChannel` to `stable` in your config file and reload Hyper.

Cheers.

**Comment by delcore92** [comment]
I'm just going to close this issue for now. Reach out to me in the Hyper Community slack if you need any help :)
