### ISSUE TITLE
Uncaught exception TypeError

### ISSUE THREAD

**Issue by rahulaakash26** [bnb/awesome-hyper#332]
A javascipt error occurs in the main process when trying to access the menu items. Also, hyper crashes after the error has been displayed.
![capture2](https://user-images.githubusercontent.com/27017547/39614823-54f376ae-4f90-11e8-9d71-a4ae74b86cf8.JPG)

**Comment by danieldelcore** [comment]
Hi @rahulaakash26,

Could you please raise this issue here: https://github.com/zeit/hyper/issues so that the right people can help you. You could even reach out people directly on the [Zeit Community Slack](https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwj2jM707vjWAhUFjpQKHcDiDuAQFggmMAA&url=https%3A%2F%2Fzeit.chat%2F&usg=AOvVaw2zp8lFpz7EH3vvRk6qs6tX)

This repo does not actually contain any code for Hyper Term, it's just a place for people to come and find plugins to use with Hyper.

Going to close this issue 👍
